# Exported from Render on 2024-07-28T20:36:50Z
services:
- type: web
  name: car-sales-app-server
  runtime: node
  repo: https://github.com/KotlinDevIanBore/car-sales-app-server
  plan: free
  envVars:
  - key: DB_PORT
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_HOST
    sync: false
  - key: DB_DATABASE
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: node index.mjs
version: "1"
